# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app-register-cpf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app-register-cpf
  pod 'SwiftLint'
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.2.1'

  target 'app-register-cpfTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'app-register-cpfUITests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
